name: Flutter Pipeline for Centrage App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.19.5

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze
      
      - name: Run tests
        run: flutter test --machine -r json > test-results.json

      - name: publish test artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: test-results
          path: test-results.json
      
      - name: Display test report
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Report
          path: test-results.json
          reporter: flutter-json

      - name: Build APK
        run: flutter build apk --release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/app-release.apk
